import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx global>
        {`
          .HomeImg {
            border-radius: 50%;
            cursor: pointer;
          }
          .imgWrapper {
            padding: 1rem;
          }
          h3 {
            font-size: 2rem;   
        
      </Footer>
          }
        `}
      </style>
      <Head>
        <title>Dog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="umit" content="createad by umit" />
        <meta name="google-site-verification" content="4amUQim6ymJ23qYYpGs0FmbYtrD9rOoKbUxieML-tY4" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Dogs</h1>
        <div className="imgWrapper">
          <Image
            className="HomeImg"
            src="/home.jpg"
            width={272}
            height={152}
            alt="Home"
          />
        </div>
        <p className={`${styles.description}`}>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam
          praesentium sapiente tempora provident accusamus nemo porro distinctio
          minima omnis saepe. Sint, saepe quam voluptas cum ipsa veritatis
          voluptate maxime cumque qui minima, temporibus nulla! Tempore aliquam,
          aperiam laudantium sit veritatis animi, rerum sed at ratione, labore
          illo quam blanditiis sapiente?
        </p>
        <Link href="/Blog">
          <button className={styles.btn}>Read More</button>
        </Link>
      </main>
    </div>
  );
}
